### PR TITLE
Add Green Algorithms CPU TDP data

### PR DESCRIPTION
**Pull request by skrakau**
Add Green Algorithms CPU TDP data and added test.

### CODE REVIEW

**Review by mirpedrol — APPROVED** [review]
🚀

**Review by Llannelongue — APPROVED** [review]
Looks great :)

**Comment by skrakau** [comment]
Note to myself: skip first line of TDP CSV file, since it contains additional comments and might change in the future.

**Comment by skrakau** [comment]
I added another small commit to skip the first line, do you want to have a look again, can I merge?

**Comment by Llannelongue** [comment]
Looks good!

**Pull request merged**
